import type {  ConfigType, Message, MessageDir, MessageRole, Config, Profile } from "@prisma/client";


export type MProfile = (Profile & { messages: Message[]; } & { _count: { messages: number } })


export interface ScoredSearchResult{

    searchResult:SearchResult
    quality:number
    value:number
}


// ASIN_DATA_API types generated by AI
interface Price {
    symbol: string;
    value: number;
    currency: string;
    raw: string;
    name?: string;
    is_primary?: boolean;
    is_rrp?: boolean;
    is_free?: boolean;
    asin?: string;
    link?: string;
}

interface Category {
    name: string;
    id: string;
}

interface Delivery {
    tagline: string;
    price?: Price;
}

interface BestSeller {
    link: string;
    category: string;
}

interface Carousel {
    title: string;
    sub_title: string;
    sponsored: boolean;
    id: string;
    total_items: number;
}

export interface SearchResult {
    position: number;
    title: string;
    asin: string;
    link: string;
    categories: Category[];
    image: string;
    is_prime?: boolean;
    rating?: number;
    ratings_total?: number;
    sponsored?: boolean;
    prices?: Price[];
    price: Price;
    delivery?: Delivery;
    is_small_business?: boolean;
    bestseller?: BestSeller;
    is_carousel?: boolean;
    carousel?: Carousel;
}

interface RelatedSearch {
    query: string;
    link: string;
}

interface Brand {
    logo: string;
    image: string;
    title: string;
    link: string;
    store_link: string;
    store_id: string;
    store_name: string;
}

interface Pagination {
    total_results: number;
    current_page: number;
    next_page_link: string;
    total_pages: number;
}

interface Refinement {
    name: string;
    value: string;
    link: string;
    refinement_display_name: string;
}

interface Refinements {
    prime: Refinement[];
    delivery: Refinement[];
    departments: Refinement[];
    reviews: Refinement[];
    price: Refinement[];
    brand: Refinement[];
    marking_pen_water_resistance_level: Refinement[];
    subscription_options: Refinement[];
    from_our_brands: Refinement[];
    packaging_option: Refinement[];
    amazon_global_store: Refinement[];
    international_shipping: Refinement[];
    condition: Refinement[];
    customizable_products: Refinement[];
    availability: Refinement[];
}

interface ShoppingAdvisorRecommendationProduct {
    title: string;
    asin: string;
    link: string;
    image: string;
    is_prime: boolean;
    rating: number;
    ratings_total: number;
    price: Price;
}

interface ShoppingAdvisorRecommendation {
    position: number;
    title: string;
    product: ShoppingAdvisorRecommendationProduct;
}

interface ShoppingAdvisor {
    position: number;
    title: string;
    recommendations: ShoppingAdvisorRecommendation[];
}

interface AdBlockProduct {
    asin: string;
    link: string;
    image: string;
    is_prime: boolean;
    rating: number;
    ratings_total: number;
}

interface AdBlock {
    campaign_id: string;
    brand_logo: string;
    background_image: string;
    advertiser_id: string;
    ad_id: string;
    link: string;
    title: string;
    store_link: string;
    store_id: string;
    store_name: string;
    products: AdBlockProduct[];
}

interface VideoBlock {
    video_link: string;
    thumbnail_link: string;
    campaign_id: string;
    advertiser_id: string;
    has_audio: boolean;
    store_name: string;
    store_link: string;
    store_id: string;
    products: AdBlockProduct[]; // Products in video block are similar to those in AdBlock
}

export interface SearchResponse {
    request_info: {
        success: boolean;
        credits_used: number;
        credits_remaining: number;
        credits_reset_at: string;
    };
    request_parameters: {
        type: string;
        amazon_domain: string;
        search_term: string;
    };
    request_metadata: {
        created_at: string;
        processed_at: string;
        total_time_taken: number;
        amazon_url: string;
    };
    search_results: SearchResult[];
    related_searches: RelatedSearch[];
    related_brands: Brand[];
    pagination: Pagination;
    refinements: Refinements;
    shopping_advisors: ShoppingAdvisor[];
    ad_blocks: AdBlock[];
    video_blocks: VideoBlock[];
}